apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: environmental-fuchsia-harrier
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: environmental-fuchsia-harrier 
  name: environmental-fuchsia-harrier
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: environmental-fuchsia-harrier
    weight: 100 
