apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: environmental-fuchsia-harrier
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: environmental-fuchsia-harrier 
  name: environmental-fuchsia-harrier
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: environmental-fuchsia-harrier 
